version: '2'
services:
  apache:
    image: php:apache
    volumes:
    - "./src/:/var/www/html"
    - "./config/:/etc/apache2/sites-available"
    links:
    - mysql
    ports:
    - "8080:80"
    privileged: true
    environment:
      - APACHE_DOCUMENT_ROOT /var/www/html/assets

  mysql:
    image: mysql:latest
    volumes:
    - "./data/:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: passroot
    privileged: true
